[package]
name = "ssh_tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
async-trait = "0.1.83"
rand = "0.8.5"
rand_core = "0.6.4"
ratatui = "0.29.0"
russh = "0.48.2"
russh-keys = "0.48.1"
ssh-key = "0.6.7"
tokio = "1.42.0"
